"""PackIntel Database Seeding Script for MongoDB Atlas.

Connects to MongoDB Atlas using MONGODB_URI and MONGODB_DB_NAME.
Seeds realistic packaging materials, food commodities, and food intelligence profiles.
Safe to run repeatedly (idempotent upserts).
"""
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from dotenv import load_dotenv

# Ensure backend root is on sys.path
SCRIPT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = SCRIPT_DIR.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# Load .env from backend/.env or root .env
load_dotenv(BACKEND_DIR / ".env")
load_dotenv(BACKEND_DIR.parent / ".env")

from pymongo import MongoClient, ASCENDING, DESCENDING
from app.database.food_knowledge import PROFILES

REFERENCE_DISCLAIMER = (
    "Reference / demo material-property data (indicative literature ranges, not lab-validated). "
    "Exact industrial values depend on manufacturer, resin grade, additives, thickness, test standard and conditions."
)

SEED_PACKAGING_MATERIALS = [
    {
        "id": 1,
        "material_name": "LDPE",
        "material_category": "Polyolefin film",
        "category": "Polyolefin film",
        "description": "Low-density polyethylene film. Flexible, tough, easily heat-sealed, with moderate moisture barrier and high gas permeability.",
        "min_thickness": 25.0,
        "max_thickness": 100.0,
        "thickness": {"min": 25.0, "max": 100.0},
        "otr_min": 3000.0,
        "otr_max": 8000.0,
        "OTR": {"min": 3000.0, "max": 8000.0, "unit": "cm3/m2/day"},
        "wvtr_min": 10.0,
        "wvtr_max": 20.0,
        "WVTR": {"min": 10.0, "max": 20.0, "unit": "g/m2/day"},
        "sealability": 5,
        "mechanical_strength": 3,
        "tensile_strength": 3,
        "gas_permeability": 4,
        "moisture_barrier": 3,
        "oxygen_barrier": 1,
        "map_suitability": 3,
        "MAP_suitability": 3,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": False,
        "sustainability_score": 3,
        "relative_cost": 1,
        "approximate_cost": 1,
        "suitable_food_categories": ["Fresh Produce", "Grains", "Bakery", "Processed Food"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "temperature_range": "-30°C to 60°C",
        "packaging_structure": "LDPE heat-sealed film pouch",
        "product_forms": ["solid", "liquid", "semi_solid", "powder"],
        "transparency": "Transparent",
        "light_protection": False,
        "food_contact_suitability": "Food-contact grade LDPE complies with standard migration limits; requires seal integrity verification.",
        "notes": "Widely used for produce bags, bread bags, and frozen food pouches. High oxygen permeability limits shelf life for oxygen-sensitive items.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 2,
        "material_name": "HDPE",
        "material_category": "Polyolefin film",
        "category": "Polyolefin film",
        "description": "High-density polyethylene. Stiff, high moisture barrier, good puncture and chemical resistance.",
        "min_thickness": 15.0,
        "max_thickness": 150.0,
        "thickness": {"min": 15.0, "max": 150.0},
        "otr_min": 1500.0,
        "otr_max": 3000.0,
        "OTR": {"min": 1500.0, "max": 3000.0, "unit": "cm3/m2/day"},
        "wvtr_min": 4.0,
        "wvtr_max": 10.0,
        "WVTR": {"min": 4.0, "max": 10.0, "unit": "g/m2/day"},
        "sealability": 4,
        "mechanical_strength": 4,
        "tensile_strength": 4,
        "gas_permeability": 3,
        "moisture_barrier": 4,
        "oxygen_barrier": 2,
        "map_suitability": 2,
        "MAP_suitability": 2,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": False,
        "sustainability_score": 3,
        "relative_cost": 1,
        "approximate_cost": 1,
        "suitable_food_categories": ["Grains", "Powdered Food", "Dairy", "Processed Food", "Snacks"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "temperature_range": "-40°C to 90°C",
        "packaging_structure": "HDPE film bag or liner",
        "product_forms": ["solid", "liquid", "powder"],
        "transparency": "Translucent",
        "light_protection": False,
        "food_contact_suitability": "Commonly food-contact certified; closure integrity requires verification.",
        "notes": "Used for cereal bag liners, grain sacks, and milk pouches. Moderate gas permeability.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 3,
        "material_name": "PET",
        "material_category": "Polyester film / rigid",
        "category": "Polyester film / rigid",
        "description": "Polyethylene terephthalate. High tensile strength, clarity, dimensional stability, moderate oxygen barrier.",
        "min_thickness": 12.0,
        "max_thickness": 50.0,
        "thickness": {"min": 12.0, "max": 50.0},
        "otr_min": 50.0,
        "otr_max": 130.0,
        "OTR": {"min": 50.0, "max": 130.0, "unit": "cm3/m2/day"},
        "wvtr_min": 15.0,
        "wvtr_max": 30.0,
        "WVTR": {"min": 15.0, "max": 30.0, "unit": "g/m2/day"},
        "sealability": 2,
        "mechanical_strength": 5,
        "tensile_strength": 5,
        "gas_permeability": 2,
        "moisture_barrier": 2,
        "oxygen_barrier": 3,
        "map_suitability": 3,
        "MAP_suitability": 3,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": False,
        "sustainability_score": 4,
        "relative_cost": 2,
        "approximate_cost": 2,
        "suitable_food_categories": ["Bakery", "Snacks", "Processed Food", "Fresh Produce", "Dairy"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "temperature_range": "-20°C to 120°C",
        "packaging_structure": "PET structure with compatible sealant layer",
        "product_forms": ["solid"],
        "transparency": "Transparent",
        "light_protection": False,
        "food_contact_suitability": "Widely approved food-contact material. Heat-sealing requires a coating or polyolefin sealant layer.",
        "notes": "Commonly laminated with PE or metallized films for enhanced sealability and barrier.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 4,
        "material_name": "PP",
        "material_category": "Polyolefin film",
        "category": "Polyolefin film",
        "description": "Polypropylene (cast PP/CPP). High gloss, good stiffness, low density, good moisture barrier.",
        "min_thickness": 20.0,
        "max_thickness": 60.0,
        "thickness": {"min": 20.0, "max": 60.0},
        "otr_min": 1500.0,
        "otr_max": 2500.0,
        "OTR": {"min": 1500.0, "max": 2500.0, "unit": "cm3/m2/day"},
        "wvtr_min": 4.0,
        "wvtr_max": 8.0,
        "WVTR": {"min": 4.0, "max": 8.0, "unit": "g/m2/day"},
        "sealability": 3,
        "mechanical_strength": 4,
        "tensile_strength": 4,
        "gas_permeability": 3,
        "moisture_barrier": 4,
        "oxygen_barrier": 2,
        "map_suitability": 3,
        "MAP_suitability": 3,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": False,
        "sustainability_score": 3,
        "relative_cost": 2,
        "approximate_cost": 2,
        "suitable_food_categories": ["Snacks", "Bakery", "Grains", "Fresh Produce", "Processed Food"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "0°C to 100°C",
        "packaging_structure": "BOPP/CPP sealable film structure",
        "product_forms": ["solid", "powder"],
        "transparency": "Transparent",
        "light_protection": False,
        "food_contact_suitability": "Food-grade PP has excellent grease/chemical resistance; embrittles below 0°C.",
        "notes": "Homopolymer PP is not recommended for freezer conditions unless impact-modified.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 5,
        "material_name": "BOPP",
        "material_category": "Biaxially oriented film",
        "category": "Biaxially oriented film",
        "description": "Biaxially oriented polypropylene film. Outstanding clarity, high stiffness, superior moisture barrier, excellent printability.",
        "min_thickness": 15.0,
        "max_thickness": 40.0,
        "thickness": {"min": 15.0, "max": 40.0},
        "otr_min": 1200.0,
        "otr_max": 2000.0,
        "OTR": {"min": 1200.0, "max": 2000.0, "unit": "cm3/m2/day"},
        "wvtr_min": 3.0,
        "wvtr_max": 6.0,
        "WVTR": {"min": 3.0, "max": 6.0, "unit": "g/m2/day"},
        "sealability": 4,
        "mechanical_strength": 4,
        "tensile_strength": 5,
        "gas_permeability": 3,
        "moisture_barrier": 4,
        "oxygen_barrier": 2,
        "map_suitability": 3,
        "MAP_suitability": 3,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": False,
        "sustainability_score": 3,
        "relative_cost": 2,
        "approximate_cost": 2,
        "suitable_food_categories": ["Snacks", "Bakery", "Confectionery", "Grains"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "5°C to 85°C",
        "packaging_structure": "BOPP heat-sealable printed overwrap",
        "product_forms": ["solid"],
        "transparency": "Transparent",
        "light_protection": False,
        "food_contact_suitability": "Coextruded heat-sealable skin layers meet food-contact criteria.",
        "notes": "Prime material for snack flow-wraps, biscuit wrappers, and pasta packaging.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 6,
        "material_name": "Metallized Film",
        "material_category": "Barrier film",
        "category": "Barrier film",
        "description": "Vacuum-metallized PET or BOPP film. Sub-micron aluminum deposition provides high moisture, light, and aroma barrier.",
        "min_thickness": 12.0,
        "max_thickness": 30.0,
        "thickness": {"min": 12.0, "max": 30.0},
        "otr_min": 0.5,
        "otr_max": 5.0,
        "OTR": {"min": 0.5, "max": 5.0, "unit": "cm3/m2/day"},
        "wvtr_min": 0.5,
        "wvtr_max": 2.0,
        "WVTR": {"min": 0.5, "max": 2.0, "unit": "g/m2/day"},
        "sealability": 3,
        "mechanical_strength": 4,
        "tensile_strength": 4,
        "gas_permeability": 1,
        "moisture_barrier": 5,
        "oxygen_barrier": 4,
        "map_suitability": 4,
        "MAP_suitability": 4,
        "recyclable": False,
        "recyclability": False,
        "biodegradable": False,
        "sustainability_score": 2,
        "relative_cost": 3,
        "approximate_cost": 3,
        "suitable_food_categories": ["Snacks", "Bakery", "Powdered Food", "Processed Food", "Dairy"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "-10°C to 80°C",
        "packaging_structure": "Metallized PET/BOPP with food-contact sealant layer",
        "product_forms": ["solid", "powder"],
        "transparency": "Opaque",
        "light_protection": True,
        "food_contact_suitability": "Requires food-contact sealant layer on product side; aluminum deposition is on substrate outer or intermediate face.",
        "notes": "Standard for potato crisps, biscuits, and coffee. Flex-cracking can reduce barrier properties.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 7,
        "material_name": "Aluminum Foil Laminate",
        "material_category": "Multilayer laminate",
        "category": "Multilayer laminate",
        "description": "PET / Aluminum Foil / PE laminate. Near-zero permeability to moisture, oxygen, UV light, and aroma compounds.",
        "min_thickness": 50.0,
        "max_thickness": 150.0,
        "thickness": {"min": 50.0, "max": 150.0},
        "otr_min": 0.01,
        "otr_max": 0.5,
        "OTR": {"min": 0.01, "max": 0.5, "unit": "cm3/m2/day"},
        "wvtr_min": 0.01,
        "wvtr_max": 0.5,
        "WVTR": {"min": 0.01, "max": 0.5, "unit": "g/m2/day"},
        "sealability": 5,
        "mechanical_strength": 4,
        "tensile_strength": 4,
        "gas_permeability": 1,
        "moisture_barrier": 5,
        "oxygen_barrier": 5,
        "map_suitability": 3,
        "MAP_suitability": 3,
        "recyclable": False,
        "recyclability": False,
        "biodegradable": False,
        "sustainability_score": 1,
        "relative_cost": 5,
        "approximate_cost": 5,
        "suitable_food_categories": ["Powdered Food", "Dairy", "Snacks", "Processed Food"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "temperature_range": "-40°C to 121°C",
        "packaging_structure": "PET / aluminium foil / food-contact PE laminate",
        "product_forms": ["solid", "liquid", "semi_solid", "powder"],
        "transparency": "Opaque",
        "light_protection": True,
        "food_contact_suitability": "Inner PE layer provides robust hermetic seals and complies with direct food contact regulations.",
        "notes": "Gold standard for long shelf-life dry powders, retortable ready-to-eat pouches, and pharmaceuticals.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 8,
        "material_name": "Paper-Based Packaging",
        "material_category": "Paper-based structure",
        "category": "Paper-based structure",
        "description": "Opaque virgin kraft paper structure with breathable design or functional bio-barrier. Renewable and recyclable.",
        "min_thickness": 80.0,
        "max_thickness": 180.0,
        "thickness": {"min": 80.0, "max": 180.0},
        "otr_min": 10000.0,
        "otr_max": 200000.0,
        "OTR": {"min": 10000.0, "max": 200000.0, "unit": "cm3/m2/day"},
        "wvtr_min": 100.0,
        "wvtr_max": 500.0,
        "WVTR": {"min": 100.0, "max": 500.0, "unit": "g/m2/day"},
        "sealability": 1,
        "mechanical_strength": 3,
        "tensile_strength": 3,
        "gas_permeability": 3,
        "moisture_barrier": 1,
        "oxygen_barrier": 1,
        "map_suitability": 1,
        "MAP_suitability": 1,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": True,
        "sustainability_score": 5,
        "relative_cost": 1,
        "approximate_cost": 1,
        "suitable_food_categories": ["Fresh Produce", "Grains", "Bakery"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "0°C to 70°C",
        "packaging_structure": "Ventilated kraft-paper bag with light shielding",
        "product_forms": ["solid"],
        "transparency": "Opaque",
        "light_protection": True,
        "food_contact_suitability": "Virgin food-contact paper required. Mechanical strength degrades significantly in humid or wet conditions.",
        "notes": "Excellent for potatoes, onions, and dry flour. Not suitable for liquids, high humidity transport, or hermetic MAP.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 9,
        "material_name": "Biodegradable Film",
        "material_category": "Bio-based film",
        "category": "Bio-based film",
        "description": "PLA / PBAT-based bio-polyester film. Renewable feedstock, bio-degradable under industrial conditions.",
        "min_thickness": 20.0,
        "max_thickness": 50.0,
        "thickness": {"min": 20.0, "max": 50.0},
        "otr_min": 400.0,
        "otr_max": 800.0,
        "OTR": {"min": 400.0, "max": 800.0, "unit": "cm3/m2/day"},
        "wvtr_min": 150.0,
        "wvtr_max": 350.0,
        "WVTR": {"min": 150.0, "max": 350.0, "unit": "g/m2/day"},
        "sealability": 3,
        "mechanical_strength": 2,
        "tensile_strength": 2,
        "gas_permeability": 4,
        "moisture_barrier": 1,
        "oxygen_barrier": 2,
        "map_suitability": 3,
        "MAP_suitability": 3,
        "recyclable": False,
        "recyclability": False,
        "biodegradable": True,
        "sustainability_score": 4,
        "relative_cost": 4,
        "approximate_cost": 4,
        "suitable_food_categories": ["Fresh Produce", "Bakery"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "-10°C to 45°C",
        "packaging_structure": "PLA/PBAT compostable film pouch",
        "product_forms": ["solid"],
        "transparency": "Grade-dependent",
        "light_protection": False,
        "food_contact_suitability": "Certified bio-resins comply with EN 13432 and food contact standards.",
        "notes": "Suited to short shelf-life produce and fresh bakery items. Low moisture barrier requires monitoring in dry climates.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 10,
        "material_name": "Compostable Film",
        "material_category": "Bio-based film",
        "category": "Bio-based film",
        "description": "Home and industrial compostable starch/PBAT blend film. Naturally degrades without microplastic residue.",
        "min_thickness": 20.0,
        "max_thickness": 60.0,
        "thickness": {"min": 20.0, "max": 60.0},
        "otr_min": 350.0,
        "otr_max": 750.0,
        "OTR": {"min": 350.0, "max": 750.0, "unit": "cm3/m2/day"},
        "wvtr_min": 120.0,
        "wvtr_max": 300.0,
        "WVTR": {"min": 120.0, "max": 300.0, "unit": "g/m2/day"},
        "sealability": 3,
        "mechanical_strength": 3,
        "tensile_strength": 3,
        "gas_permeability": 4,
        "moisture_barrier": 2,
        "oxygen_barrier": 2,
        "map_suitability": 3,
        "MAP_suitability": 3,
        "recyclable": False,
        "recyclability": False,
        "biodegradable": True,
        "sustainability_score": 5,
        "relative_cost": 4,
        "approximate_cost": 4,
        "suitable_food_categories": ["Fresh Produce", "Bakery", "Snacks"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "-5°C to 50°C",
        "packaging_structure": "Home-compostable barrier film wrap",
        "product_forms": ["solid"],
        "transparency": "Translucent",
        "light_protection": False,
        "food_contact_suitability": "Certified food-safe bio-polyester blends.",
        "notes": "Ideal for organic fruits, vegetables, and eco-friendly brand lines.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 11,
        "material_name": "Breathable Film",
        "material_category": "Breathable film",
        "category": "Breathable film",
        "description": "Tailored microporous polyolefin membrane allowing controlled moisture vapor transmission while restricting liquid ingress.",
        "min_thickness": 25.0,
        "max_thickness": 70.0,
        "thickness": {"min": 25.0, "max": 70.0},
        "otr_min": 5000.0,
        "otr_max": 50000.0,
        "OTR": {"min": 5000.0, "max": 50000.0, "unit": "cm3/m2/day"},
        "wvtr_min": 40.0,
        "wvtr_max": 200.0,
        "WVTR": {"min": 40.0, "max": 200.0, "unit": "g/m2/day"},
        "sealability": 4,
        "mechanical_strength": 3,
        "tensile_strength": 3,
        "gas_permeability": 5,
        "moisture_barrier": 2,
        "oxygen_barrier": 1,
        "map_suitability": 4,
        "MAP_suitability": 4,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": False,
        "sustainability_score": 3,
        "relative_cost": 3,
        "approximate_cost": 3,
        "suitable_food_categories": ["Fresh Produce", "Bakery"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "2°C to 25°C",
        "packaging_structure": "Microporous breathable produce film",
        "product_forms": ["solid"],
        "transparency": "Translucent",
        "light_protection": False,
        "food_contact_suitability": "FDA and EU 10/2011 food-contact compliant microporous polyolefin.",
        "notes": "Prevents fogging and in-pack condensation in high-respiration produce such as mushrooms, berries, and broccoli.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 12,
        "material_name": "Micro-Perforated Film",
        "material_category": "Breathable film",
        "category": "Breathable film",
        "description": "LDPE or BOPP film with precision laser micro-perforations tuned for controlled atmosphere equilibration with respiring produce.",
        "min_thickness": 20.0,
        "max_thickness": 50.0,
        "thickness": {"min": 20.0, "max": 50.0},
        "otr_min": 10000.0,
        "otr_max": 200000.0,
        "OTR": {"min": 10000.0, "max": 200000.0, "unit": "cm3/m2/day"},
        "wvtr_min": 10.0,
        "wvtr_max": 60.0,
        "WVTR": {"min": 10.0, "max": 60.0, "unit": "g/m2/day"},
        "sealability": 4,
        "mechanical_strength": 3,
        "tensile_strength": 3,
        "gas_permeability": 5,
        "moisture_barrier": 3,
        "oxygen_barrier": 1,
        "map_suitability": 5,
        "MAP_suitability": 5,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": False,
        "sustainability_score": 3,
        "relative_cost": 3,
        "approximate_cost": 3,
        "suitable_food_categories": ["Fresh Produce"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "0°C to 25°C",
        "packaging_structure": "Micro-perforated LDPE/BOPP film",
        "product_forms": ["solid"],
        "transparency": "Transparent",
        "light_protection": False,
        "food_contact_suitability": "Certified food-grade polyolefin base film.",
        "notes": "Targeted for equilibrium modified atmosphere packaging (EMAP) of fresh fruits and vegetables.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 13,
        "material_name": "High-Barrier Laminate",
        "material_category": "Multilayer laminate",
        "category": "Multilayer laminate",
        "description": "Multi-layer coextrusion with EVOH or polyamide barrier core (e.g., PET/EVOH/PE). Exceptional oxygen barrier with high seal integrity.",
        "min_thickness": 60.0,
        "max_thickness": 150.0,
        "thickness": {"min": 60.0, "max": 150.0},
        "otr_min": 0.5,
        "otr_max": 5.0,
        "OTR": {"min": 0.5, "max": 5.0, "unit": "cm3/m2/day"},
        "wvtr_min": 1.0,
        "wvtr_max": 5.0,
        "WVTR": {"min": 1.0, "max": 5.0, "unit": "g/m2/day"},
        "sealability": 5,
        "mechanical_strength": 5,
        "tensile_strength": 5,
        "gas_permeability": 1,
        "moisture_barrier": 4,
        "oxygen_barrier": 5,
        "map_suitability": 5,
        "MAP_suitability": 5,
        "recyclable": False,
        "recyclability": False,
        "biodegradable": False,
        "sustainability_score": 2,
        "relative_cost": 4,
        "approximate_cost": 4,
        "suitable_food_categories": ["Dairy", "Processed Food", "Snacks", "Powdered Food", "Bakery"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "temperature_range": "-30°C to 100°C",
        "packaging_structure": "PET / EVOH / PE barrier pouch",
        "product_forms": ["solid", "liquid", "semi_solid", "powder"],
        "transparency": "Grade-dependent",
        "light_protection": False,
        "food_contact_suitability": "PE inner sealant layer complies with global food contact standards.",
        "notes": "Primary choice for nitrogen or carbon dioxide flushed modified atmosphere packaging (MAP) of meats, cheeses, and sensitive foods.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 14,
        "material_name": "PP Cup with Sealed Lid",
        "material_category": "Rigid food-contact structure",
        "category": "Rigid food-contact structure",
        "description": "Thermoformed polypropylene tub or cup with sealed foil/polymer lidding. High chemical, acid, and temperature resilience.",
        "min_thickness": 400.0,
        "max_thickness": 900.0,
        "thickness": {"min": 400.0, "max": 900.0},
        "otr_min": 50.0,
        "otr_max": 250.0,
        "OTR": {"min": 50.0, "max": 250.0, "unit": "cm3/m2/day"},
        "wvtr_min": 0.5,
        "wvtr_max": 3.0,
        "WVTR": {"min": 0.5, "max": 3.0, "unit": "g/m2/day"},
        "sealability": 5,
        "mechanical_strength": 4,
        "tensile_strength": 4,
        "gas_permeability": 2,
        "moisture_barrier": 4,
        "oxygen_barrier": 3,
        "map_suitability": 3,
        "MAP_suitability": 3,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": False,
        "sustainability_score": 4,
        "relative_cost": 2,
        "approximate_cost": 2,
        "suitable_food_categories": ["Dairy", "Processed Food"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "0°C to 100°C",
        "packaging_structure": "Food-contact PP cup with compatible sealed lid",
        "product_forms": ["semi_solid", "solid"],
        "transparency": "Grade-dependent",
        "light_protection": False,
        "food_contact_suitability": "Food-contact grade PP container with heat-sealed peelable membrane.",
        "notes": "Standard container for yogurts, curd, desserts, dips, and ready-to-eat sauces.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
    {
        "id": 15,
        "material_name": "Opaque HDPE Bottle",
        "material_category": "Rigid food-contact structure",
        "category": "Rigid food-contact structure",
        "description": "Blow-molded opaque high-density polyethylene bottle with induction-sealed closure for light-sensitive liquid foods.",
        "min_thickness": 500.0,
        "max_thickness": 1200.0,
        "thickness": {"min": 500.0, "max": 1200.0},
        "otr_min": 50.0,
        "otr_max": 300.0,
        "OTR": {"min": 50.0, "max": 300.0, "unit": "cm3/m2/day"},
        "wvtr_min": 0.5,
        "wvtr_max": 4.0,
        "WVTR": {"min": 0.5, "max": 4.0, "unit": "g/m2/day"},
        "sealability": 4,
        "mechanical_strength": 5,
        "tensile_strength": 5,
        "gas_permeability": 2,
        "moisture_barrier": 4,
        "oxygen_barrier": 2,
        "map_suitability": 2,
        "MAP_suitability": 2,
        "recyclable": True,
        "recyclability": True,
        "biodegradable": False,
        "sustainability_score": 4,
        "relative_cost": 2,
        "approximate_cost": 2,
        "suitable_food_categories": ["Dairy", "Processed Food"],
        "suitable_storage_types": ["ambient", "chilled"],
        "temperature_range": "-20°C to 80°C",
        "packaging_structure": "Opaque HDPE bottle with sealed food-contact closure",
        "product_forms": ["liquid"],
        "transparency": "Opaque",
        "light_protection": True,
        "food_contact_suitability": "Certified virgin food-contact HDPE resin. Requires torque-monitored closure.",
        "notes": "Industry standard for fresh pasteurized milk, edible oils, juices, and liquid dairy.",
        "data_provenance": REFERENCE_DISCLAIMER,
    },
]

SEED_FOOD_COMMODITIES = [
    {"id": 1, "commodity_name": "Tomato", "category": "Fresh Produce", "typical_moisture": 94.0, "typical_oil_content": 0.2, "typical_ph": 4.3, "respiration_level": "high", "moisture_sensitivity": "high", "oxygen_sensitivity": "medium", "notes": "Climacteric fruit. Sensitive to chilling injury below 10°C."},
    {"id": 2, "commodity_name": "Potato", "category": "Fresh Produce", "typical_moisture": 79.0, "typical_oil_content": 0.1, "typical_ph": 5.8, "respiration_level": "low", "moisture_sensitivity": "medium", "oxygen_sensitivity": "low", "notes": "Store in the dark to prevent solanine greening. Requires air circulation."},
    {"id": 3, "commodity_name": "Apple", "category": "Fresh Produce", "typical_moisture": 85.0, "typical_oil_content": 0.2, "typical_ph": 3.5, "respiration_level": "medium", "moisture_sensitivity": "medium", "oxygen_sensitivity": "medium", "notes": "Climacteric fruit with ethylene production. Benefits from controlled atmospheres."},
    {"id": 4, "commodity_name": "Banana", "category": "Fresh Produce", "typical_moisture": 75.0, "typical_oil_content": 0.3, "typical_ph": 4.8, "respiration_level": "high", "moisture_sensitivity": "medium", "oxygen_sensitivity": "medium", "notes": "Climacteric tropical fruit. High chilling injury risk below 13°C."},
    {"id": 5, "commodity_name": "Rice", "category": "Grains", "typical_moisture": 12.0, "typical_oil_content": 0.7, "typical_ph": 6.5, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "low", "notes": "Hygroscopic cereal grain. Moisture ingress triggers mold and infestation."},
    {"id": 6, "commodity_name": "Pulses", "category": "Grains", "typical_moisture": 10.0, "typical_oil_content": 1.5, "typical_ph": 6.5, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "low", "notes": "Dry legumes. Protect from ambient relative humidity and pest activity."},
    {"id": 7, "commodity_name": "Biscuits", "category": "Bakery", "typical_moisture": 3.0, "typical_oil_content": 20.0, "typical_ph": 6.8, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "medium", "notes": "Crisp dry bakery product. Moisture pickup causes staling; fat is vulnerable to rancidity."},
    {"id": 8, "commodity_name": "Chips", "category": "Snacks", "typical_moisture": 2.0, "typical_oil_content": 35.0, "typical_ph": 6.5, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "high", "notes": "High fat snack food. Requires nitrogen gas flushing and light-shielding barrier."},
    {"id": 9, "commodity_name": "Spices", "category": "Powdered Food", "typical_moisture": 9.0, "typical_oil_content": 10.0, "typical_ph": 5.5, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "medium", "notes": "Contains delicate volatile essential oils. Requires high aroma and light barriers."},
    {"id": 10, "commodity_name": "Milk Powder", "category": "Powdered Food", "typical_moisture": 3.0, "typical_oil_content": 26.0, "typical_ph": 6.7, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "high", "notes": "Hygroscopic spray-dried powder. Fat oxidizes rapidly in presence of oxygen and moisture."},
    {"id": 11, "commodity_name": "Milk", "category": "Dairy", "typical_moisture": 88.0, "typical_oil_content": 3.8, "typical_ph": 6.6, "respiration_level": "low", "moisture_sensitivity": "low", "oxygen_sensitivity": "medium", "notes": "Perishable liquid dairy. Requires strict 4°C cold chain and light shielding against riboflavin oxidation."},
    {"id": 12, "commodity_name": "Curd", "category": "Dairy", "typical_moisture": 85.0, "typical_oil_content": 4.0, "typical_ph": 4.4, "respiration_level": "low", "moisture_sensitivity": "low", "oxygen_sensitivity": "low", "notes": "Fermented semi-solid dairy. Mildly acidic; requires sealed food-grade container."},
    {"id": 13, "commodity_name": "Bread", "category": "Bakery", "typical_moisture": 38.0, "typical_oil_content": 3.0, "typical_ph": 5.5, "respiration_level": "low", "moisture_sensitivity": "medium", "oxygen_sensitivity": "medium", "notes": "Intermediate moisture food. Balances moisture retention against mold proliferation."},
    {"id": 14, "commodity_name": "Cheese", "category": "Dairy", "typical_moisture": 37.0, "typical_oil_content": 30.0, "typical_ph": 5.2, "respiration_level": "low", "moisture_sensitivity": "medium", "oxygen_sensitivity": "high", "notes": "Semi-hard dairy. High fat content; MAP with CO2/N2 retards surface mold growth."},
]


def seed_database():
    uri = os.environ.get("MONGODB_URI") or os.environ.get("MONGO_URL")
    db_name = os.environ.get("MONGODB_DB_NAME") or os.environ.get("DB_NAME") or "packintel"

    if not uri:
        print("[ERROR] MONGODB_URI environment variable is not set!")
        print("Please configure MONGODB_URI in your backend/.env file before seeding.")
        sys.exit(1)

    print(f"[*] Connecting to MongoDB Atlas ({db_name})...")
    client = MongoClient(uri, serverSelectionTimeoutMS=8000)

    try:
        client.admin.command("ping")
        print("[+] MongoDB Atlas connection verified successfully!")
    except Exception as exc:
        print(f"[ERROR] Could not connect to MongoDB: {exc}")
        sys.exit(1)

    db = client[db_name]

    # Ensure required indexes
    print("[*] Creating / verifying collection indexes...")
    db.packaging_materials.create_index([("id", ASCENDING)], unique=True, sparse=True)
    db.packaging_materials.create_index([("material_name", ASCENDING)], unique=True)
    db.packaging_materials.create_index([("material_category", ASCENDING)])
    db.packaging_materials.create_index([("suitable_food_categories", ASCENDING)])

    db.food_commodities.create_index([("id", ASCENDING)], unique=True, sparse=True)
    db.food_commodities.create_index([("commodity_name", ASCENDING)], unique=True)
    db.food_commodities.create_index([("category", ASCENDING)])

    db.food_profiles.create_index([("food_name", ASCENDING)], unique=True)

    db.recommendations.create_index([("id", DESCENDING)], unique=True, sparse=True)
    db.recommendations.create_index([("created_at", DESCENDING)])

    db.prediction_history.create_index([("id", DESCENDING)], unique=True, sparse=True)
    db.prediction_history.create_index([("created_at", DESCENDING)])

    db.food_images.create_index([("id", ASCENDING)], unique=True)
    db.feedback.create_index([("created_at", DESCENDING)])

    # Seed packaging_materials
    print(f"[*] Seeding {len(SEED_PACKAGING_MATERIALS)} packaging materials...")
    mat_count = 0
    now = datetime.now(timezone.utc)
    for mat in SEED_PACKAGING_MATERIALS:
        doc = {**mat, "updated_at": now}
        db.packaging_materials.update_one(
            {"material_name": mat["material_name"]},
            {"$set": doc, "$setOnInsert": {"created_at": now}},
            upsert=True,
        )
        mat_count += 1
    print(f"[+] Seeded {mat_count} packaging materials into collection 'packaging_materials'.")

    # Seed food_commodities
    print(f"[*] Seeding {len(SEED_FOOD_COMMODITIES)} food commodities...")
    com_count = 0
    for com in SEED_FOOD_COMMODITIES:
        doc = {**com, "updated_at": now}
        db.food_commodities.update_one(
            {"commodity_name": com["commodity_name"]},
            {"$set": doc, "$setOnInsert": {"created_at": now}},
            upsert=True,
        )
        com_count += 1
    print(f"[+] Seeded {com_count} commodities into collection 'food_commodities'.")

    # Seed food_profiles knowledge base
    print(f"[*] Seeding {len(PROFILES)} food intelligence profiles...")
    prof_count = 0
    for food_name, profile in PROFILES.items():
        doc = {
            "food_name": food_name,
            "profile": profile.model_dump(mode="json"),
            "updated_at": now,
        }
        db.food_profiles.update_one(
            {"food_name": food_name},
            {"$set": doc, "$setOnInsert": {"created_at": now}},
            upsert=True,
        )
        prof_count += 1
    print(f"[+] Seeded {prof_count} profiles into collection 'food_profiles'.")

    client.close()
    print("\n=======================================================")
    print("  PackIntel Database Seeding Completed Successfully!  ")
    print("=======================================================")


if __name__ == "__main__":
    seed_database()
