-- Reference / prototype data (indicative ranges, not experimentally validated). Generated file.

INSERT INTO packaging_materials (material_name, material_category, description, min_thickness, max_thickness, otr_min, otr_max, wvtr_min, wvtr_max, sealability, mechanical_strength, gas_permeability, moisture_barrier, oxygen_barrier, map_suitability, recyclable, biodegradable, relative_cost, suitable_food_categories, suitable_storage_types, notes) VALUES
  ('LDPE', 'Polyolefin film', 'Low-density polyethylene film. Flexible, tough and easily heat-sealed, with a moderate moisture barrier and high gas permeability.', 25, 100, 3000, 8000, 10, 20, 5, 3, 4, 3, 1, 3, TRUE, FALSE, 1, ARRAY['Fresh Produce', 'Grains', 'Bakery', 'Processed Food']::TEXT[], ARRAY['ambient', 'chilled', 'frozen']::TEXT[], 'Common for produce bags, bread bags and frozen-food bags. Poor oxygen barrier.'),
  ('HDPE', 'Polyolefin film', 'High-density polyethylene. Stiffer than LDPE with a better moisture barrier and good puncture resistance; widely used for bulk sacks and liners.', 15, 150, 1500, 3000, 4, 10, 4, 4, 3, 4, 2, 2, TRUE, FALSE, 1, ARRAY['Grains', 'Powdered Food', 'Dairy', 'Processed Food', 'Snacks']::TEXT[], ARRAY['ambient', 'chilled', 'frozen']::TEXT[], 'Used for grain and flour liners, cereal liners and milk pouches. Limited oxygen barrier.'),
  ('PET', 'Polyester film / rigid', 'Polyethylene terephthalate. High strength, clarity and dimensional stability, with a moderate oxygen barrier and relatively low moisture barrier.', 12, 50, 50, 130, 15, 30, 2, 5, 2, 2, 3, 3, TRUE, FALSE, 2, ARRAY['Bakery', 'Snacks', 'Processed Food', 'Fresh Produce', 'Dairy']::TEXT[], ARRAY['ambient', 'chilled', 'frozen']::TEXT[], 'Needs a sealant layer or coating for heat sealing. Used for trays, clamshells and laminate outer layers.'),
  ('PP', 'Polyolefin film', 'Polypropylene film (BOPP/CPP). Good clarity, stiffness and moisture barrier, with moderate gas permeability.', 20, 60, 1500, 2500, 4, 8, 3, 4, 3, 4, 2, 3, TRUE, FALSE, 2, ARRAY['Snacks', 'Bakery', 'Grains', 'Fresh Produce', 'Processed Food']::TEXT[], ARRAY['ambient', 'chilled']::TEXT[], 'Homopolymer PP becomes brittle at freezer temperatures; not rated for frozen storage here.'),
  ('Metallized Film', 'Barrier film', 'Vacuum-metallized PET or BOPP. Thin aluminium coating gives a high moisture, light and oxygen barrier at lower cost than foil.', 12, 30, 0.5, 5, 0.5, 2, 3, 4, 1, 5, 4, 4, FALSE, FALSE, 3, ARRAY['Snacks', 'Bakery', 'Powdered Food', 'Processed Food', 'Dairy']::TEXT[], ARRAY['ambient', 'chilled']::TEXT[], 'Standard for chips and biscuits; compatible with nitrogen flushing. Barrier drops if the coating cracks when flexed.'),
  ('Aluminum Foil Laminate', 'Multilayer laminate', 'PET/Al foil/PE laminate. Near-total barrier to moisture, oxygen and light, with a strong PE sealant layer.', 50, 150, 0.01, 0.5, 0.01, 0.5, 5, 4, 1, 5, 5, 3, FALSE, FALSE, 5, ARRAY['Powdered Food', 'Dairy', 'Snacks', 'Processed Food']::TEXT[], ARRAY['ambient', 'chilled', 'frozen']::TEXT[], 'Used for milk powder, spices, coffee and retort pouches. Multi-material structure is hard to recycle.'),
  ('Biodegradable Film', 'Bio-based film', 'PLA / PBAT-based compostable film. Renewable or compostable, but with a low moisture barrier and limited mechanical strength.', 20, 50, 400, 800, 150, 350, 3, 2, 4, 1, 2, 3, FALSE, TRUE, 4, ARRAY['Fresh Produce', 'Bakery']::TEXT[], ARRAY['ambient', 'chilled']::TEXT[], 'Needs industrial composting to biodegrade. Suited to short shelf-life products.'),
  ('Micro-Perforated Film', 'Breathable film', 'LDPE or BOPP film with laser micro-perforations that set the rate of O2/CO2 exchange for respiring produce.', 20, 50, 10000, 200000, 10, 60, 4, 3, 5, 3, 1, 5, TRUE, FALSE, 3, ARRAY['Fresh Produce']::TEXT[], ARRAY['ambient', 'chilled']::TEXT[], 'Effective OTR depends on the number and size of perforations. Used for passive MAP of fruits and vegetables.'),
  ('High-Barrier Laminate', 'Multilayer laminate', 'Coextruded or laminated structure with an EVOH or PA barrier layer (e.g. PET/EVOH/PE). Very high oxygen barrier and strong seals.', 60, 150, 0.5, 5, 1, 5, 5, 5, 1, 4, 5, 5, FALSE, FALSE, 4, ARRAY['Dairy', 'Processed Food', 'Snacks', 'Powdered Food', 'Bakery']::TEXT[], ARRAY['ambient', 'chilled', 'frozen']::TEXT[], 'EVOH''s oxygen barrier weakens at high humidity unless protected by outer layers. Used for gas-flushed MAP.'),
  ('Paper-Based Ventilated Bag', 'Paper-based structure', 'Opaque kraft-paper bag with ventilation openings; limits light exposure while allowing air exchange. Not a liquid or high-humidity barrier pack.', 80, 180, 10000, 200000, 100, 500, 1, 3, 3, 1, 1, 1, TRUE, TRUE, 1, ARRAY['Fresh Produce', 'Grains']::TEXT[], ARRAY['ambient', 'chilled']::TEXT[], 'Ventilated whole-pack transmission depends on openings. Paper strength drops when wet. Use food-contact grade; coatings can change recyclability.'),
  ('PP Cup with Sealed Lid', 'Rigid food-contact structure', 'Food-contact polypropylene cup with a compatible heat-sealed polymer or coated-foil lid for refrigerated semi-solid foods.', 400, 900, 50, 250, 0.5, 3, 5, 4, 2, 4, 3, 3, TRUE, FALSE, 2, ARRAY['Dairy', 'Processed Food']::TEXT[], ARRAY['ambient', 'chilled']::TEXT[], 'Indicative wall thickness and wall transmission only; assembled lid/seal performance must be tested. Acid compatibility depends on the contact-grade polymer, lid coating and seal. Separate lid for recycling where accepted.'),
  ('Opaque HDPE Bottle', 'Rigid food-contact structure', 'Opaque food-contact HDPE bottle with a tamper-evident sealed closure, for liquid foods requiring light shielding.', 500, 1200, 50, 300, 0.5, 4, 4, 5, 2, 4, 2, 2, TRUE, FALSE, 2, ARRAY['Dairy', 'Processed Food']::TEXT[], ARRAY['ambient', 'chilled']::TEXT[], 'Indicative bottle-wall ranges, not whole-bottle test data. Closure integrity and oxygen ingress need validation; not an aseptic UHT process.')
ON CONFLICT (material_name) DO NOTHING;

INSERT INTO commodities (commodity_name, category, typical_moisture, typical_oil_content, typical_ph, respiration_level, moisture_sensitivity, oxygen_sensitivity, notes) VALUES
  ('Tomato', 'Fresh Produce', 94, 0.2, 4.3, 'high', 'high', 'medium', 'Climacteric fruit. Sensitive to chilling injury below about 10 C when mature-green.'),
  ('Potato', 'Fresh Produce', 79, 0.1, 5.8, 'low', 'medium', 'low', 'Store in the dark to prevent greening. Needs ventilation.'),
  ('Apple', 'Fresh Produce', 85, 0.2, 3.5, 'medium', 'medium', 'medium', 'Climacteric fruit that produces ethylene. Responds well to controlled atmospheres.'),
  ('Banana', 'Fresh Produce', 75, 0.3, 4.8, 'high', 'medium', 'medium', 'Climacteric fruit. Chilling-sensitive below about 13 C.'),
  ('Rice', 'Grains', 12, 0.7, 6.5, 'low', 'high', 'low', 'Hygroscopic. Moisture pick-up raises the risk of mould and insect activity.'),
  ('Pulses', 'Grains', 10, 1.5, 6.5, 'low', 'high', 'low', 'Low-moisture dry commodity. Protect from humidity and insects.'),
  ('Biscuits', 'Bakery', 3, 20, 6.8, 'low', 'high', 'medium', 'Loses crispness when it absorbs moisture. Fat is prone to oxidation.'),
  ('Chips', 'Snacks', 2, 35, 6.5, 'low', 'high', 'high', 'High fat content. Prone to rancidity and loss of crispness. Usually nitrogen-flushed.'),
  ('Spices', 'Powdered Food', 9, 10, 5.5, 'low', 'high', 'medium', 'Volatile aroma compounds. Protect from moisture, light and aroma loss.'),
  ('Milk Powder', 'Powdered Food', 3, 26, 6.7, 'low', 'high', 'high', 'Hygroscopic, and cakes when it absorbs moisture. Milk fat is prone to oxidation.')
ON CONFLICT (commodity_name) DO NOTHING;
