"""Reference / prototype material-property data (indicative literature ranges, not lab-validated).

Single source for database/seed.sql (via scripts/generate_seed.py) and the offline fallback.
Ratings are ordinal 1 (poor) to 5 (excellent). gas_permeability: 5 = most breathable.
OTR in cm3/m2/day (23 C, 0% RH), WVTR in g/m2/day (38 C, 90% RH), thickness in micrometres.
"""

MATERIALS = [
    {
        "material_name": "LDPE",
        "material_category": "Polyolefin film",
        "description": "Low-density polyethylene film. Flexible, tough and easily heat-sealed, with a moderate "
        "moisture barrier and high gas permeability.",
        "min_thickness": 25, "max_thickness": 100,
        "otr_min": 3000, "otr_max": 8000, "wvtr_min": 10, "wvtr_max": 20,
        "sealability": 5, "mechanical_strength": 3, "gas_permeability": 4,
        "moisture_barrier": 3, "oxygen_barrier": 1, "map_suitability": 3,
        "recyclable": True, "biodegradable": False, "relative_cost": 1,
        "suitable_food_categories": ["Fresh Produce", "Grains", "Bakery", "Processed Food"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "notes": "Common for produce bags, bread bags and frozen-food bags. Poor oxygen barrier.",
    },
    {
        "material_name": "HDPE",
        "material_category": "Polyolefin film",
        "description": "High-density polyethylene. Stiffer than LDPE with a better moisture barrier and good "
        "puncture resistance; widely used for bulk sacks and liners.",
        "min_thickness": 15, "max_thickness": 150,
        "otr_min": 1500, "otr_max": 3000, "wvtr_min": 4, "wvtr_max": 10,
        "sealability": 4, "mechanical_strength": 4, "gas_permeability": 3,
        "moisture_barrier": 4, "oxygen_barrier": 2, "map_suitability": 2,
        "recyclable": True, "biodegradable": False, "relative_cost": 1,
        "suitable_food_categories": ["Grains", "Powdered Food", "Dairy", "Processed Food", "Snacks"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "notes": "Used for grain and flour liners, cereal liners and milk pouches. Limited oxygen barrier.",
    },
    {
        "material_name": "PET",
        "material_category": "Polyester film / rigid",
        "description": "Polyethylene terephthalate. High strength, clarity and dimensional stability, with a "
        "moderate oxygen barrier and relatively low moisture barrier.",
        "min_thickness": 12, "max_thickness": 50,
        "otr_min": 50, "otr_max": 130, "wvtr_min": 15, "wvtr_max": 30,
        "sealability": 2, "mechanical_strength": 5, "gas_permeability": 2,
        "moisture_barrier": 2, "oxygen_barrier": 3, "map_suitability": 3,
        "recyclable": True, "biodegradable": False, "relative_cost": 2,
        "suitable_food_categories": ["Bakery", "Snacks", "Processed Food", "Fresh Produce", "Dairy"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "notes": "Needs a sealant layer or coating for heat sealing. Used for trays, clamshells and laminate outer layers.",
    },
    {
        "material_name": "PP",
        "material_category": "Polyolefin film",
        "description": "Polypropylene film (BOPP/CPP). Good clarity, stiffness and moisture barrier, with moderate "
        "gas permeability.",
        "min_thickness": 20, "max_thickness": 60,
        "otr_min": 1500, "otr_max": 2500, "wvtr_min": 4, "wvtr_max": 8,
        "sealability": 3, "mechanical_strength": 4, "gas_permeability": 3,
        "moisture_barrier": 4, "oxygen_barrier": 2, "map_suitability": 3,
        "recyclable": True, "biodegradable": False, "relative_cost": 2,
        "suitable_food_categories": ["Snacks", "Bakery", "Grains", "Fresh Produce", "Processed Food"],
        "suitable_storage_types": ["ambient", "chilled"],
        "notes": "Homopolymer PP becomes brittle at freezer temperatures; not rated for frozen storage here.",
    },
    {
        "material_name": "Metallized Film",
        "material_category": "Barrier film",
        "description": "Vacuum-metallized PET or BOPP. Thin aluminium coating gives a high moisture, light and "
        "oxygen barrier at lower cost than foil.",
        "min_thickness": 12, "max_thickness": 30,
        "otr_min": 0.5, "otr_max": 5, "wvtr_min": 0.5, "wvtr_max": 2,
        "sealability": 3, "mechanical_strength": 4, "gas_permeability": 1,
        "moisture_barrier": 5, "oxygen_barrier": 4, "map_suitability": 4,
        "recyclable": False, "biodegradable": False, "relative_cost": 3,
        "suitable_food_categories": ["Snacks", "Bakery", "Powdered Food", "Processed Food", "Dairy"],
        "suitable_storage_types": ["ambient", "chilled"],
        "notes": "Standard for chips and biscuits; compatible with nitrogen flushing. Barrier drops if the coating cracks when flexed.",
    },
    {
        "material_name": "Aluminum Foil Laminate",
        "material_category": "Multilayer laminate",
        "description": "PET/Al foil/PE laminate. Near-total barrier to moisture, oxygen and light, with a strong "
        "PE sealant layer.",
        "min_thickness": 50, "max_thickness": 150,
        "otr_min": 0.01, "otr_max": 0.5, "wvtr_min": 0.01, "wvtr_max": 0.5,
        "sealability": 5, "mechanical_strength": 4, "gas_permeability": 1,
        "moisture_barrier": 5, "oxygen_barrier": 5, "map_suitability": 3,
        "recyclable": False, "biodegradable": False, "relative_cost": 5,
        "suitable_food_categories": ["Powdered Food", "Dairy", "Snacks", "Processed Food"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "notes": "Used for milk powder, spices, coffee and retort pouches. Multi-material structure is hard to recycle.",
    },
    {
        "material_name": "Biodegradable Film",
        "material_category": "Bio-based film",
        "description": "PLA / PBAT-based compostable film. Renewable or compostable, but with a low moisture barrier "
        "and limited mechanical strength.",
        "min_thickness": 20, "max_thickness": 50,
        "otr_min": 400, "otr_max": 800, "wvtr_min": 150, "wvtr_max": 350,
        "sealability": 3, "mechanical_strength": 2, "gas_permeability": 4,
        "moisture_barrier": 1, "oxygen_barrier": 2, "map_suitability": 3,
        "recyclable": False, "biodegradable": True, "relative_cost": 4,
        "suitable_food_categories": ["Fresh Produce", "Bakery"],
        "suitable_storage_types": ["ambient", "chilled"],
        "notes": "Needs industrial composting to biodegrade. Suited to short shelf-life products.",
    },
    {
        "material_name": "Micro-Perforated Film",
        "material_category": "Breathable film",
        "description": "LDPE or BOPP film with laser micro-perforations that set the rate of O2/CO2 exchange for "
        "respiring produce.",
        "min_thickness": 20, "max_thickness": 50,
        "otr_min": 10000, "otr_max": 200000, "wvtr_min": 10, "wvtr_max": 60,
        "sealability": 4, "mechanical_strength": 3, "gas_permeability": 5,
        "moisture_barrier": 3, "oxygen_barrier": 1, "map_suitability": 5,
        "recyclable": True, "biodegradable": False, "relative_cost": 3,
        "suitable_food_categories": ["Fresh Produce"],
        "suitable_storage_types": ["ambient", "chilled"],
        "notes": "Effective OTR depends on the number and size of perforations. Used for passive MAP of fruits and vegetables.",
    },
    {
        "material_name": "High-Barrier Laminate",
        "material_category": "Multilayer laminate",
        "description": "Coextruded or laminated structure with an EVOH or PA barrier layer (e.g. PET/EVOH/PE). Very "
        "high oxygen barrier and strong seals.",
        "min_thickness": 60, "max_thickness": 150,
        "otr_min": 0.5, "otr_max": 5, "wvtr_min": 1, "wvtr_max": 5,
        "sealability": 5, "mechanical_strength": 5, "gas_permeability": 1,
        "moisture_barrier": 4, "oxygen_barrier": 5, "map_suitability": 5,
        "recyclable": False, "biodegradable": False, "relative_cost": 4,
        "suitable_food_categories": ["Dairy", "Processed Food", "Snacks", "Powdered Food", "Bakery"],
        "suitable_storage_types": ["ambient", "chilled", "frozen"],
        "notes": "EVOH's oxygen barrier weakens at high humidity unless protected by outer layers. Used for gas-flushed MAP.",
    },
    {
        "material_name": "Paper-Based Ventilated Bag", "material_category": "Paper-based structure",
        "description": "Opaque kraft-paper bag with ventilation openings; limits light exposure while allowing air exchange. Not a liquid or high-humidity barrier pack.",
        "min_thickness": 80, "max_thickness": 180, "otr_min": 10000, "otr_max": 200000,
        "wvtr_min": 100, "wvtr_max": 500, "sealability": 1, "mechanical_strength": 3,
        "gas_permeability": 3, "moisture_barrier": 1, "oxygen_barrier": 1, "map_suitability": 1,
        "recyclable": True, "biodegradable": True, "relative_cost": 1,
        "suitable_food_categories": ["Fresh Produce", "Grains"], "suitable_storage_types": ["ambient", "chilled"],
        "notes": "Ventilated whole-pack transmission depends on openings. Paper strength drops when wet. Use food-contact grade; coatings can change recyclability."
    },
    {
        "material_name": "PP Cup with Sealed Lid", "material_category": "Rigid food-contact structure",
        "description": "Food-contact polypropylene cup with a compatible heat-sealed polymer or coated-foil lid for refrigerated semi-solid foods.",
        "min_thickness": 400, "max_thickness": 900, "otr_min": 50, "otr_max": 250,
        "wvtr_min": 0.5, "wvtr_max": 3, "sealability": 5, "mechanical_strength": 4,
        "gas_permeability": 2, "moisture_barrier": 4, "oxygen_barrier": 3, "map_suitability": 3,
        "recyclable": True, "biodegradable": False, "relative_cost": 2,
        "suitable_food_categories": ["Dairy", "Processed Food"], "suitable_storage_types": ["ambient", "chilled"],
        "notes": "Indicative wall thickness and wall transmission only; assembled lid/seal performance must be tested. Acid compatibility depends on the contact-grade polymer, lid coating and seal. Separate lid for recycling where accepted."
    },
    {
        "material_name": "Opaque HDPE Bottle", "material_category": "Rigid food-contact structure",
        "description": "Opaque food-contact HDPE bottle with a tamper-evident sealed closure, for liquid foods requiring light shielding.",
        "min_thickness": 500, "max_thickness": 1200, "otr_min": 50, "otr_max": 300,
        "wvtr_min": 0.5, "wvtr_max": 4, "sealability": 4, "mechanical_strength": 5,
        "gas_permeability": 2, "moisture_barrier": 4, "oxygen_barrier": 2, "map_suitability": 2,
        "recyclable": True, "biodegradable": False, "relative_cost": 2,
        "suitable_food_categories": ["Dairy", "Processed Food"], "suitable_storage_types": ["ambient", "chilled"],
        "notes": "Indicative bottle-wall ranges, not whole-bottle test data. Closure integrity and oxygen ingress need validation; not an aseptic UHT process."
    },
]

COMMODITIES = [
    {"commodity_name": "Tomato", "category": "Fresh Produce", "typical_moisture": 94, "typical_oil_content": 0.2,
     "typical_ph": 4.3, "respiration_level": "high", "moisture_sensitivity": "high", "oxygen_sensitivity": "medium",
     "notes": "Climacteric fruit. Sensitive to chilling injury below about 10 C when mature-green."},
    {"commodity_name": "Potato", "category": "Fresh Produce", "typical_moisture": 79, "typical_oil_content": 0.1,
     "typical_ph": 5.8, "respiration_level": "low", "moisture_sensitivity": "medium", "oxygen_sensitivity": "low",
     "notes": "Store in the dark to prevent greening. Needs ventilation."},
    {"commodity_name": "Apple", "category": "Fresh Produce", "typical_moisture": 85, "typical_oil_content": 0.2,
     "typical_ph": 3.5, "respiration_level": "medium", "moisture_sensitivity": "medium", "oxygen_sensitivity": "medium",
     "notes": "Climacteric fruit that produces ethylene. Responds well to controlled atmospheres."},
    {"commodity_name": "Banana", "category": "Fresh Produce", "typical_moisture": 75, "typical_oil_content": 0.3,
     "typical_ph": 4.8, "respiration_level": "high", "moisture_sensitivity": "medium", "oxygen_sensitivity": "medium",
     "notes": "Climacteric fruit. Chilling-sensitive below about 13 C."},
    {"commodity_name": "Rice", "category": "Grains", "typical_moisture": 12, "typical_oil_content": 0.7,
     "typical_ph": 6.5, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "low",
     "notes": "Hygroscopic. Moisture pick-up raises the risk of mould and insect activity."},
    {"commodity_name": "Pulses", "category": "Grains", "typical_moisture": 10, "typical_oil_content": 1.5,
     "typical_ph": 6.5, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "low",
     "notes": "Low-moisture dry commodity. Protect from humidity and insects."},
    {"commodity_name": "Biscuits", "category": "Bakery", "typical_moisture": 3, "typical_oil_content": 20,
     "typical_ph": 6.8, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "medium",
     "notes": "Loses crispness when it absorbs moisture. Fat is prone to oxidation."},
    {"commodity_name": "Chips", "category": "Snacks", "typical_moisture": 2, "typical_oil_content": 35,
     "typical_ph": 6.5, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "high",
     "notes": "High fat content. Prone to rancidity and loss of crispness. Usually nitrogen-flushed."},
    {"commodity_name": "Spices", "category": "Powdered Food", "typical_moisture": 9, "typical_oil_content": 10,
     "typical_ph": 5.5, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "medium",
     "notes": "Volatile aroma compounds. Protect from moisture, light and aroma loss."},
    {"commodity_name": "Milk Powder", "category": "Powdered Food", "typical_moisture": 3, "typical_oil_content": 26,
     "typical_ph": 6.7, "respiration_level": "low", "moisture_sensitivity": "high", "oxygen_sensitivity": "high",
     "notes": "Hygroscopic, and cakes when it absorbs moisture. Milk fat is prone to oxidation."},
]
